cover:
  title: Q's Notebook
  display:
    home: true
    archive: true
    others: true
  layout_scheme: dock
  features:
    - name: Blog
      icon: "fa fa-blog"
      url: /
    - name: Archive
      icon: "fa fa-box-archive"
      url: /archives/
    - name: About
      icon: "fa fa-info"
      url: /about/

navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: 
    icon: "fa fa-q"
    title:
  menu:
    - name: Blog
      icon: "fa fa-blog"
      url: /
    - name: Archive
      icon: "fa fa-box-archive"
      url: /archives/
    - name: About
      icon: "fa fa-info"
      url: /about/
    - name: Switch Mode
      icon: "fa fa-moon"
      toggle: darkmode

sidebar:
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: /images/head.png
      title: Q
      subtitle: aka Mashio
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      # Do not listen to their official document, you have to add the item detail. Set social as true of false won't work
      social: 
        - icon: fas fa-window-maximize
          url: http://mattq.net
        - icon: fas fa-envelope
          url: mailto:uzenkyu@gmail.com
        - icon: fab fa-github
          url: https://github.com/qiumatthew
        - icon: fas fa-headphones-alt
          url: https://music.163.com/#/user/home?id=278306010

plugins:
  # multiple cover images
  parallax:
    enable: true
    position: fixed
    shuffle: false
    duration: 10000
    fade: 500
    images: 
      - /images/cover.jpg
  # dark mode
  darkmode:
    enable: true

color_scheme:
  # é€šç”¨é¢œè‰²
  common:
    # ä¸»é¢˜è‰²
    theme: '#3dd9b6'
    # é“¾æ¥è‰²
    link: '#2092ec'
    # æŒ‰é’®è‰²
    button: '#44D7B6'
    # é¼ æ ‡æ”¾åˆ°äº¤äº’å…ƒç´ ä¸Šæ—¶çš„è‰²
    hover: '#ff5722'
    # ä¸»é¢˜è‰²å—å†…éƒ¨çš„æ–‡å­—é¢œè‰²
    inner: '#fff'
    # é€‰ä¸­åŒºåŸŸæ–‡å­—çš„èƒŒæ™¯é¢œè‰²
    selection: 'alpha(#2196f3, 0.2)'
  # ------------
  # äº®è‰²ä¸»é¢˜ï¼ˆé»˜è®¤ï¼‰
  light:
    # ç½‘ç«™èƒŒæ™¯è‰²
    site_bg: '#f4f4f4'
    # ç½‘ç«™èƒŒæ™¯ä¸Šçš„æ–‡å­—
    site_inner: '#fff'
    # ç½‘ç«™é¡µè„šæ–‡å­—
    site_footer: '#666'

    # å¡ç‰‡èƒŒæ™¯è‰²
    card: '#fff'
    # å¡ç‰‡ä¸Šçš„æ™®é€šæ–‡å­—
    text: '#444'

    # åŒºå—å’Œä»£ç å—èƒŒæ™¯è‰²
    block: '#f6f6f6'
    # ä»£ç å—é«˜äº®æ—¶çš„èƒŒæ™¯è‰²
    codeblock: '#FFF7EA'
    # è¡Œå†…ä»£ç é¢œè‰²
    inlinecode: '#c74f00'

    # æ–‡ç« éƒ¨åˆ†
    h1: '#3a3a3a'
    h2: '#3a3a3a'
    h3: '#333'
    h4: '#444'
    h5: '#555'
    h6: '#666'
    p: '#444'

    # åˆ—è¡¨æ–‡å­—
    list: '#666'
    # åˆ—è¡¨ hover æ—¶çš„æ–‡å­—
    list_hl: 'mix($color-theme, #000, 80)'
    # è¾…åŠ©æ€§æ–‡å­—
    meta: '#888'
    
    # ç‰ˆæƒå¡ç‰‡èƒŒæ™¯è‰²
    copyright_bkg: '#f5f5f5'
  # ------------
  # æš—è‰²ä¸»é¢˜
  # https://www.maijisheji.com/2094.html
  dark:
    # ç½‘ç«™æœ€æ·±åº•è‰²            # Dark Grey 1
    site_bd: '#121212'
    # ç½‘ç«™èƒŒæ™¯è‰²              # Dark Grey 2
    site_bg: '#1f1f1f'
    # å¡ç‰‡èƒŒæ™¯è‰²              # Dark Grey 3
    card: '#262626'
    # ç½‘ç«™èƒŒæ™¯ä¸Šçš„æ–‡å­—
    site_inner: '#eeeeeede'
    # ç½‘ç«™é¡µè„šæ–‡å­—
    site_footer: '#aaaaaade'
    # å¡ç‰‡ä¸Šçš„æ™®é€šæ–‡å­—
    text: '#eeeeeede'

    # åŒºå—å’Œä»£ç å—èƒŒæ™¯è‰²       # Dark Grey 4
    block: '#434343'
    # ä»£ç å—é«˜äº®æ—¶çš„èƒŒæ™¯è‰²     # Dark Grey 2
    codeblock: '#1f1f1f'
    # è¡Œå†…ä»£ç é¢œè‰²
    inlinecode: '#D56D28'

    # æ–‡ç« éƒ¨åˆ† é«˜å¼ºåº¦æ–‡æœ¬çš„ä¸é€æ˜åº¦åº”ä¸º87ï¼… ä¸­ç­‰é‡ç‚¹æ–‡å­—é€‚ç”¨äº60ï¼…
    h1: '#FFFFFFde'            #  Dark Grey 8
    h2: '#FFFFFFde'
    h3: '#FFFFFF99'            #  Dark Grey 7
    h4: '#FFFFFF99'
    h5: '#FFFFFF99'
    h6: '#FFFFFF99'
    p: '#d9d9d9de'           #  Dark Grey 6

    # åˆ—è¡¨æ–‡å­—                #  Dark Grey 6
    list: '#d9d9d9de'
    # åˆ—è¡¨ hover æ—¶çš„æ–‡å­—
    list_hl: 'mix($color-theme, #fff, 80)'
    # è¾…åŠ©æ€§æ–‡å­—              #  Dark Grey 5
    meta: '#bfbfbfde'
    # ç‰ˆæƒå¡ç‰‡èƒŒæ™¯è‰²
    copyright_bkg: '#21252b'
    # å¤œé—´å›¾ç‰‡äº®åº¦
    brightness: 70%

site_footer:
  #https://volantis.js.org/v6/theme-settings/#%E8%AE%BE%E7%BD%AE%E7%BD%91%E7%AB%99%E9%A1%B5%E8%84%9A
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, info, copyright]
  social:
    - icon: fas fa-window-maximize
      url: http://mattq.net
    - icon: fas fa-envelope
      url: mailto:uzenkyu@gmail.com
    - icon: fab fa-github
      url: https://github.com/qiumatthew
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=278306010
  copyright: '[Copyright © 2024-2024 Q](/)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'


comments:
  title: <i class='fa-solid fa-comments'></i> Comments
  subtitle:
  service: giscus
  # giscus
  # https://giscus.app
  # https://github.com/laymonage/giscus
  giscus:
    # ?????? yml ????????
    repo: qiumatthew/qiumatthew.github.io
    # repo-id: xxx
    # category: xxx
    # category-id: xxx
    # mapping: "pathname"
    # reactions-enabled: "1"
    # emit-metadata: "0"
    # lang: "zh-CN"
    # ?????? yml ????????
    theme:
      light: "light" # https://gcore.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/light.css
      dark: "dark" # https://gcore.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/dark.css

pages:
  friends:
    layout_scheme: traditional

article:
  body:
    meta_library:
      author:
        avatar: /images/head.png
        name: "Author: Q"
      date:
        icon: fa-solid fa-calendar-alt
        title: "Initially Posted: "
        format: "ll"
      updated:
        icon: fa-solid fa-edit
        title: "Last Updated: "
        format: "ll"
      share:

# https://volantis.js.org/v6/theme-settings/#%E7%AB%99%E5%86%85%E6%90%9C%E7%B4%A2
# need hexo-generator-json-content
search:
  enable: true
  service: hexo
